version: '2.3'

services:
  openluup-slim-master:
    image: openluup:master-slim
    build:
      context: ./openluup-debian
    ports:
      - "3480:3480"
    # environment:
    #   # Set the variable USER_DATA_JSON to provide a custom user_data.json file.
    #   # This will make openLuup initialize its userdata from this json file.
    #   # Notes:
    #   # - Configuration updates will not be update to this file.
    #   # - Plugins used in the configuration will not be installed automatically
    #   - USER_DATA_JSON=/etc/cmh-lu/my_user_data.json
    restart: unless-stopped
    volumes:
      # The openLuup environment is stored in the container as /etc/cmh-ludl/
      # This directory contains the plugins and user_data.
      - type: volume
        source: cmh-ludl
        target: /etc/cmh-ludl/
      # To add custom plugin code, a local directory can be mounted as /etc/cmh-lu/
      - type: bind
        source: ./cmh-lu
        target: /etc/cmh-lu/
      # To access logs and backups, use the respective volume mounts:
      - cmh-ludl-logs:/etc/cmh-ludl/logs/
      - cmh-ludl-backup:/etc/cmh-ludl/backup/

  openluup-slim-development:
    image: openluup:development-slim
    extends:
      service: openluup-slim-master
    build:
      args:
        - OPENLUUP_BRANCH=development

  openluup-alpine-master:
    image: openluup:master-alpine
    extends:
      service: openluup-slim-master
    build:
      context: ./openluup-alpine

  openluup-alpine-development:
    image: openluup:development-alpine
    extends:
      service: openluup-alpine-master
    build:
      args:
        - OPENLUUP_BRANCH=development

volumes:
  # The volume cmh-ludl will contain the complete openLuup environment
  # including all plugins and the user_data.json file.
  # These volumes are persistent.
  cmh-ludl:
    name: openluup-env
    labels:
      org.label-schema.description: "openLuup environment with plugins and userdata"
  cmh-ludl-logs:
    name: openluup-logs
    labels:
      org.label-schema.description: "openLuup logs"
  cmh-ludl-backup:
    name: openluup-backups
    labels:
      org.label-schema.description: "openLuup automatic backups"
